apiVersion: v1
kind: Pod
metadata:
  name: gvisor
spec:
  runtimeClassName: gvisorclass
  containers:
  - name: gvisor
    image: ubuntu:latest
    command: [ "bin/bash", "-c", "--"]
    args: 
      - apt-get update; apt upgrade; apt install -y git ssh wget net-tools vim